[tools]
biome             = "latest"
bun               = "latest"
just              = "latest"
markdownlint-cli2 = "latest"
"pipx:pre-commit" = "latest"
prettier          = "latest"
"pipx:mdformat"   = { version = "latest", uvx_args = "--with mdformat-gfm --with mdformat-admon --with mdformat-config --with mdformat-footnote --with mdformat-simple-breaks --with mdformat-web --with mdformat-ruff --with mdformat-gfm-alerts --with mdformat-toc --with mdformat-front-matters" }

# Many of these settings are defaults, but we are explicit in case they change in the future and to make it clear to users what is enabled.
[settings]
activate_aggressive                 = true
idiomatic_version_file_enable_tools = [ "python", "go", "bun" ]
env_cache                           = true
exec_auto_install                   = true
github_attestations                 = true
lockfile                            = true
pin                                 = true
slsa                                = true

[settings.npm]
package_manager = "bun"

[settings.pipx]
uvx = true
