name: Copilot Setup
"on":
  workflow_dispatch:
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.2
      - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1
        with:
          install: true
          cache: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - run: just install
      - name: Validate setup
        run: just ci-check

      - name: Display environment info
        run: just info
